datasource:
    config:
        url: "jdbc:postgresql://127.0.0.1:5432/algalog"
        username: "postgres"
        password: "postgres"
        driver-classname: "org.postgresql.Driver"
springdoc:
  version: "@org.springdoc.version@"
  swagger-ui:
    path: /swagger-ui
server:
    port: 8080