spring:
    datasource:
        url: "jdbc:postgresql://127.0.0.1:5432/algalog"
        username: "postgres"
        password: "postgres"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        show-sql: false
        hibernate:
            ddl-auto: update
server:
    port: 8080