spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        show-sql: false
        hibernate:
            ddl-auto: update
server:
    port: ${SERVER_PORT}