datasource:
    config:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-classname: ${DATABASE_DRIVER_CLASSNAME}
server:
    port: ${SERVER_PORT}